### ISSUE TITLE
HttpAdapterFactory

### ISSUE THREAD

**Issue by ddeboer** [php-http/httplug#25]
The egeloen library had an [HttpAdapterFactory](https://github.com/egeloen/ivory-http-adapter/blob/master/src/HttpAdapterFactory.php) that tries to automatically instantiate an HTTP adapter based on the HTTP client library that is installed. Should we create an php-http/adapter-factory (or adapter-guesser?) package, too?

**Comment by sagikazarmark** [comment]
Currently our idea is that adapters provide `php-http/adapter-implementation` virtual package which means requiring that should explicitly declare which http adapter you use. We haven't decided yet how we should proceed about adapter guessing. Maybe we could create a package which requires all adapter implementations provided by us and we could implement a guesser there.

**Comment by sagikazarmark** [comment]
Since the Http Adapter has been separated into actual Adapter and Client, this functionality should go into the client IMO.

**Comment by ddeboer** [comment]
Why no `AdapterGuesser` or `AdapterFactory` in adapter? That way other libs that require an HTTP client could just depend on adapter an use its `AdapterGuesser` to retrieve an adapter.

I don’t think this is top-priority though.

**Comment by sagikazarmark** [comment]
I would not add that into the contract. It is not as stable as the exceptions for example. Either in the adapter client or in a separate package.

It is rather a hack than a real solution. In an ideal case, all dependencies should always be injected instead of auto setup.

**Comment by ddeboer** [comment]
How would you handle a case like https://github.com/FriendsOfSymfony/FOSHttpCache/pull/173#discussion-diff-31533918R63?

**Comment by sagikazarmark** [comment]
Yeah, I agree the guesser could be useful in that case. Do you think putting it in a separate package is a bad idea? (Because putting one class in a separate package seems to be a bit odd)

The case I would like to avoid is to version the guesser together with the adapter, because as new adapters are created, they must be added to the guesser (which makes the adapter pretty unstable).

One thing I can think of is adding an empty guesser to the adapter contract and somehow the installed adapters could register themselves during autoloading. But this also sounds weird.

**Comment by sagikazarmark** [comment]
Maybe message-factory-guesser and adapter-guesser could moved into one package.

**Comment by sagikazarmark** [comment]
@ddeboer https://github.com/php-http/guesser

Does this solve your issue?

**Comment by ddeboer** [comment]
It definitely does!
